name: Lint and Update renovate PR

# configure trigger by pull request
on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs: 
  lint_and_update:
    if: github.event.pull_request.user.login == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Pull Request Branch
        run: gh pr checkout ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Update Helm Test
        id: update
        run: |
          make build-helm-tests
      
      - name: Check Updates
        id: check_updates
        run: |
          ./tools/find-diff-or-untracked.sh .
          echo "diff=exit-code::${?}"  # Capture exit code

      - name: Update PR
        id: update_pr
        if: steps.check_updates.outputs.diff != '0'
        run: |
            echo "Add commit to fix linting errors"
            git config --global user.email "${{ github.event.pull_request.user.login }}@users.noreply.github.com"
            git config --global user.name "${{ github.event.pull_request.user.login }}"
            git add .
            git commit -m "Update build with linting fixes"
            git push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
