### .github/workflows/member_pr.yml
### This workflow runs against target branch, which is main, so no pull request would able to modify the logic here
### unitl the pull request is merged into main
name: Membership check
on:
    # this needs to be pull_request_target, not pull_request, just put pull_request to test
    pull_request_target:
        types: [opened, synchronize]
        paths:
          - mimir-build-image/Dockerfile 
jobs:
    check-membership:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v4
        
          - name: Check user for team affiliation
            id: teamAffiliation
            run: |
                chmod +x .github/workflows/scripts/membership_check.sh
                result=$(./.github/workflows/scripts/membership_check.sh "${{ secrets.GH_BOT_ACCESS_TOKEN }}" "${{ github.triggering_actor }}")
                echo "I want to know what I am getting here $result"
                echo "team_membership=$result" >> $GITHUB_OUTPUT

          - name: Add Comment to the PR
            id: notification
            if: ${{ steps.teamAffiliation.outputs.team_membership != 'true' }}
            run: | 
                echo "the current value is?? ${{ steps.teamAffiliation.outputs.team_membership }}"
                gh pr comment $PR_NUMBER --body "You are changing docker image of mimir-build-image. And you have no right to trigger docker image build, please contact one of mimir-maintainer to review your change before preceed."
            env:
                PR_NUMBER: ${{ github.event.pull_request.number }}
                GITHUB_TOKEN: ${{secrets.GH_BOT_ACCESS_TOKEN}}

          - name: Stop workflow if user is no member
            if: ${{ steps.teamAffiliation.outputs.team_membership != 'true' }}
            run: |
              echo "You have no rights to trigger this job."
              exit 1
